/* =========================================================================
   YOUR CONTENT — generated by editor.html on 2026-07-19
   =========================================================================
   Re-open editor.html any time to make more changes, or edit the values
   below directly (this is a plain JS object, no special syntax needed).
   ========================================================================= */

window.SITE_CONTENT = {
  "meta": {
    "siteTitle": "Safaruzzaman Shovo - PhD Applicant"
  },
  "profile": {
    "name": "Safaruzzaman Shovo",
    "eyebrow": "PhD Applicant · Computer Science",
    "affiliation": "B.S. in Computer Science, University of Dhaka · Applying for Fall 2027",
    "status": "Open to PhD offers · Fall 2027 admission",
    "photo": "assets/profile.jpg",
    "abstract": "I am **Safaruzzaman Shovo**, a final-year undergraduate researcher working on Natural Language Processing (NLP) and Large Language Models (LLMs), with a focus on efficient model adaptation, multilingual and low-resource language understanding, and improving the reasoning, robustness, and generalization capabilities of foundation models. My recent work explores transformer-based models for code-mixed and low-resource language processing, aiming to develop reliable AI systems that can learn effectively from limited data and handle diverse linguistic environments. I am applying to PhD programs in Fall 2027 to pursue research on generalizable language intelligence, ideally advised by faculty working at the intersection of NLP, LLMs, deep learning, and trustworthy artificial intelligence.\n",
    "keywords": [
      "Large Language Models (LLMs)",
      "Natural Language Processing (NLP)",
      "Foundation Models",
      "Transformer-based Models",
      "Multilingual NLP",
      "Low-resource Language Processing"
    ],
    "links": [
      {
        "label": "Email",
        "url": "mailto:shovo.3052@fec.edu.bd",
        "icon": "mail"
      },
      {
        "label": "CV",
        "url": "assets/cv.pdf",
        "icon": "file"
      },
      {
        "label": "Google Scholar",
        "url": "https://scholar.google.com/citations?user=demo",
        "icon": "cap"
      },
      {
        "label": "GitHub",
        "url": "https://github.com/SafaruzzamanShovo",
        "icon": "code"
      },
      {
        "label": "LinkedIn",
        "url": "https://www.linkedin.com/in/SafaruzzamanShovo",
        "icon": "link"
      }
    ]
  },
  "researchInterests": [
    {
      "title": "Sample-Efficient Reinforcement Learning",
      "description": "Learning useful policies from limited real-world interaction."
    },
    {
      "title": "Sim-to-Real Transfer",
      "description": "Closing the gap between simulated training and physical deployment."
    },
    {
      "title": "Robotic Manipulation",
      "description": "Dexterous policies that generalize across object shapes and grasps."
    },
    {
      "title": "Human-Robot Interaction",
      "description": "Robots that learn from human demonstrations and corrections."
    }
  ],
  "skills": [
    {
      "category": "Languages",
      "items": [
        "Python",
        "C++",
        "MATLAB",
        "JavaScript"
      ]
    },
    {
      "category": "ML & Robotics",
      "items": [
        "PyTorch",
        "JAX",
        "MuJoCo",
        "ROS",
        "OpenCV"
      ]
    },
    {
      "category": "Systems & Tools",
      "items": [
        "Git",
        "Docker",
        "Linux",
        "AWS",
        "Slurm"
      ]
    }
  ],
  "education": [
    {
      "degree": "B.S. in Computer Science",
      "institution": "University of Washington",
      "period": "2022 – 2026 (expected)",
      "details": "GPA: 3.92/4.0 · Honors thesis on sample-efficient RL for manipulation, advised by Prof. David Torres"
    },
    {
      "degree": "High School Diploma",
      "institution": "Lakeside School, Seattle",
      "period": "2018 – 2022",
      "details": ""
    }
  ],
  "publications": [
    {
      "title": "Sample-Efficient Reinforcement Learning for Dexterous Manipulation via Learned Dynamics Models",
      "authors": "Maya Chen, David Torres",
      "venue": "arXiv preprint",
      "year": "2026",
      "status": "Preprint",
      "tags": [
        {
          "label": "PDF",
          "url": "#"
        },
        {
          "label": "Code",
          "url": "#"
        },
        {
          "label": "arXiv",
          "url": "#"
        }
      ]
    },
    {
      "title": "Evaluating Sim-to-Real Transfer for Quadrupedal Locomotion Policies",
      "authors": "Maya Chen, Priya Nair, David Torres",
      "venue": "UW Undergraduate Research Symposium",
      "year": "2025",
      "status": "Published",
      "tags": [
        {
          "label": "PDF",
          "url": "#"
        }
      ]
    }
  ],
  "researchExperience": [
    {
      "role": "Undergraduate Researcher, UW Robotics Lab",
      "org": "Advised by Prof. David Torres",
      "period": "Jun 2025 – Present",
      "description": "Designing a model-based RL pipeline that learns object-relative dynamics models, cutting the real-world trials needed to learn a new grasp-and-place skill by roughly 6x compared to a model-free baseline.",
      "tags": [
        "Python",
        "PyTorch",
        "MuJoCo",
        "ROS"
      ],
      "link": {
        "label": "View Code",
        "url": "https://github.com/mayachen/dexterous-rl"
      }
    },
    {
      "role": "Research Assistant, UW Robotics Lab",
      "org": "Advised by Prof. David Torres & Priya Nair",
      "period": "Sep 2024 – Jun 2025",
      "description": "Evaluated sim-to-real transfer techniques for quadrupedal locomotion, running domain-randomization sweeps across five gap configurations and building the analysis pipeline used in the resulting symposium paper.",
      "tags": [
        "Python",
        "MuJoCo",
        "Domain Randomization"
      ],
      "link": null
    }
  ],
  "projects": [
    {
      "title": "Autonomous Drone Navigation — CS Capstone",
      "period": "Sep 2024 – Jun 2025",
      "description": "Built a vision-based obstacle avoidance system for a quadrotor using a lightweight depth-estimation network, deployed and tested on real hardware in an indoor flight arena.",
      "tags": [
        "C++",
        "OpenCV",
        "PX4"
      ],
      "link": {
        "label": "Project Writeup",
        "url": "https://github.com/mayachen/drone-nav"
      }
    },
    {
      "title": "Grasp Dataset Visualizer",
      "period": "Spring 2024",
      "description": "An open-source tool for browsing large robotic grasp datasets, with side-by-side point-cloud and RGB views, built for a research methods elective.",
      "tags": [
        "Python",
        "Open3D",
        "Plotly"
      ],
      "link": {
        "label": "View Code",
        "url": "https://github.com/mayachen/grasp-viz"
      }
    }
  ],
  "blog": [
    {
      "date": "Jun 2026",
      "title": "What I Wish I Knew Before Writing PhD Statements of Purpose",
      "excerpt": "Notes on turning eighteen months of lab work into a two-page statement — what admissions committees actually seem to be reading for.",
      "url": "#"
    },
    {
      "date": "Mar 2026",
      "title": "Debugging Sim-to-Real Gaps, One Assumption at a Time",
      "excerpt": "A walkthrough of the domain-randomization sweep that finally closed the gap between our MuJoCo policies and the real quadrotor.",
      "url": "#"
    },
    {
      "date": "Nov 2025",
      "title": "Reading Group Notes: Model-Based RL for Manipulation",
      "excerpt": "A short summary of three papers our lab read this fall, and where I think the open problems still are.",
      "url": "#"
    }
  ],
  "news": [
    {
      "date": "Jul 2026",
      "text": "Submitted PhD applications for Fall 2027 admission."
    },
    {
      "date": "May 2026",
      "text": "Presented a poster on sim-to-real transfer at the UW Undergraduate Research Symposium."
    },
    {
      "date": "Jan 2026",
      "text": "Started as an undergraduate researcher in the UW Robotics Lab."
    }
  ],
  "contact": {
    "email": "maya.chen@uw.edu",
    "note": "I'm currently applying to PhD programs for Fall 2027 in robot learning and reinforcement learning. If our research interests overlap, I'd love to hear from you."
  },
  "footerText": "© {year} Safaruzzaman. Built with Love ❤️"
};
